### ISSUE TITLE
Question about SH generation

### ISSUE THREAD

**Issue by nicknikolov** [cedricpinson/envtools#16]
Hi Cedric!

I've been on a journey to understand and use spherical harmonics. Your code has been of great help to understand and implement it. One thing I am confused about is why you are multiplying your harmonics by these coefficients here https://github.com/cedricpinson/osgjs/blob/master/examples/pbr/EnvironmentSphericalHarmonics.js
rather than do it inside envtools when you generate the numbers. 

Thanks!

**Comment by cedricpinson** [comment]
No reason, it was to test different coefficient

**Comment by nicknikolov** [comment]
I see, thanks
